version: 2

project_name: vocab

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/vocab
    binary: vocab
    ldflags:
      - -s -w -H windowsgui -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - "^ci:"

release:
  github:
    owner: msaeedsaeedi
    name: vocab
  draft: false
  prerelease: auto
