// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDueWord() {
  return window['go']['main']['App']['GetDueWord']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RecordFeedback(arg1, arg2) {
  return window['go']['main']['App']['RecordFeedback'](arg1, arg2);
}
