// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDueWord() {
  return window['go']['main']['App']['GetDueWord']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function IsAutoStart() {
  return window['go']['main']['App']['IsAutoStart']();
}

export function RecordFeedback(arg1, arg2) {
  return window['go']['main']['App']['RecordFeedback'](arg1, arg2);
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
