// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDueWord():Promise<main.WordCard>;

export function GetStats():Promise<main.Stats>;

export function RecordFeedback(arg1:number,arg2:boolean):Promise<void>;
