// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.WidgetConfig>;

export function GetDueWord():Promise<main.WordCard>;

export function GetStats():Promise<main.Stats>;

export function HideToTray():Promise<void>;

export function IsAutoStart():Promise<boolean>;

export function RecordFeedback(arg1:number,arg2:boolean):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function ToggleWindow():Promise<void>;
